### ISSUE TITLE
Converting to python

### ISSUE THREAD

**Issue by mohamadnosratian** [liutianlin0121/fetalECGExtraction#2]
dude i'm trying to convert your code into pyhton.

this line : 

> y(n) = w( : , n) ' * vec_u( : , n)

from za_lms.m file
convert to : 

> y[n] = w[ : , n].conj().transpose()*vec_u[: , n]

but its give me this error :

> Traceback (most recent call last):
>   File "Process.py", line 101, in <module>
>     y, e = ZA_LMS(Abdomen_1, DI, 0.01, 0.09, 150)
>   File "Process.py", line 33, in ZA_LMS
>     y[n] = w[:, n].conj().transpose()*vec_u[n, :]

ValueError: setting an array element with a sequence.

its says that you can't set y[n] on sequence like [1,2,3,..] that results from multiplying W and vec_u.
if you can, tell me what is going on in this line, it would be great 👍

**Comment by liutianlin0121** [comment]
Hi. It seems to me that the error appears because y[n] needs to be a scalar. However, in your python implementation, the assignment `w[:, n].conj().transpose()*vec_u[n, :] ` is not a scalar. My guess is that vec_u[n, :] is supposed to be vec_u[:,n] (I am not exactly sure, though — I have not re-read me matlab code or go through the Lms algorithm again.

I am closing this issue for now because this is a problem related to Matlab->Python conversion but not related to the project itself, which is purely based on matlab. If you meet further problems on the conversion, stackoverflow seems to be a perfect platform to seek help.

**Comment by mohamadnosratian** [comment]
thank you a lot .
